version: "3.9"

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  backend:

services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: always
    networks:
      - backend
    env_file: .env
    ports:
      - ${PORT-7687}:7687
      - 7474:7474
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
    environment:
      - NEO4J_AUTH=neo4j/${PASSWORD-12345678}
