version: "3.9"

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  backend:

services:
  neo4j:
    image: neo4j:latest
    restart: always
    networks:
      - backend
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
    environment:
      - NEO4J_AUTH=neo4j/12345678
